name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: actions-runner
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
            npm ci
            npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.run_number }}
          path: |
            dist
            *firebase            
           